### ISSUE TITLE
Change Weapon Crit Range for Champion - Fighter subclass

### ISSUE THREAD

**Issue by BullitLeMans** [sillvva/Roll20-API-Scripts#3]
Love this script! I noticed when importing a DDB character with the Champion fighter subclass, the "Improved Critical" feature is not being automatically applied to weapon attacks on the Roll20 5e OGL character sheet.

Here's the [Champion subclass](https://www.dndbeyond.com/characters/classes/fighter#Champion) for reference.

Here's a screenshot of the expected behavior -- each weapon should have a Crit Range value of 19 for Fighter-Champion characters starting at Fighter Level 3. Starting at Fighter Level 15, this should be superceded by the Superior Critical feature, and set the crit range to 18.  

<img width="251" alt="screen shot 2018-09-24 at 11 17 02 am" src="https://user-images.githubusercontent.com/33738039/45964471-84bd0500-bfeb-11e8-81c7-52a539c2974f.png">

**Comment by sillvva** [comment]
Yeah, there are several features I haven't gotten to yet. I will have more time to get to them in about two weeks as I'll be going on a week-long trip starting this weekend.

**Comment by sillvva** [comment]
This has been included in version 0.3.9
